### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by kristofferbas** [custom-cards/tracker-card#12]
Trying to use the tracker card, but get the following error in the log:

http://hassio.local:8123/local/lovelace/tracker-card.js?1535014573.5867672:101:83 TypeError: undefined is not an object (evaluating 'domain.replace')

Any idea?

**Comment by ludeeus** [comment]
@kristofferbas Which version of the tracker-card and the custom_updater do you have?

**Comment by kristofferbas** [comment]
@ludeeus custom_updater is 2.2.0 and tracker-card is latest (0.1.4?).

**Comment by ludeeus** [comment]
The tracker-card gets its information from sensors, can you extract the attributes of the sensors you use?
```
sensor.custom_card_tracker
sensor.custom_component_tracker
```
Also put in the configuration for the card and component

**Comment by kristofferbas** [comment]
Looks like the error is with sensor.custom_card_tracker (it's empty in states). When I comment out that row sensor.custom_component_tracker works and displays correctly.

```
- type: custom:tracker-card
  title:
  trackers:
    - sensor.custom_card_tracker
    - sensor.custom_component_tracker
```

**Comment by ludeeus** [comment]
Then the issue is probably that it could not connect to GitHub during startup.
A restart of Home-Assistant usually solves that

**Comment by kristofferbas** [comment]
I have restarted a couple of times now, and it's the same thing every time. Strange.

**Comment by ludeeus** [comment]
Can you enable debug logging for the component https://github.com/custom-components/custom_updater#activate-debug-logging

And when it starts up run the service `custom_updater.check_all` and paste the logoutput for it here?

**Comment by kristofferbas** [comment]
The only message i get in the log is this
`2018-08-23 19:57:31 DEBUG (SyncWorker_15) [custom_components.custom_updater] Local version of custom_updater is 2.2.0`

**Comment by ludeeus** [comment]
@kristofferbas Can you paste the `resources` section of your ui-lovelace file?

**Comment by kristofferbas** [comment]
Oh, and I'm using lovelace-gen, can that has something to do with it?

```
resources:
  - url: !resource custom-cards/tracker-card.js
    type: js
  - url: !resource custom-cards/vertical-stack-in-card.js
    type: js
  - url: !resource custom-cards/slider-entity-row.js
    type: js
```

**Comment by ludeeus** [comment]
There is your problem :)
It will only find cards that have `?v=x` after it
like:
```
resources:
  - url: !resource custom-cards/tracker-card.js?v=1
    type: js
  - url: !resource custom-cards/vertical-stack-in-card.js?v=1
    type: js
  - url: !resource custom-cards/slider-entity-row.js?v=1
    type: js
```
