### ISSUE TITLE
"?? Updates" and nothing else is shown

### ISSUE THREAD

**Issue by claudioita** [custom-cards/tracker-card#13]
I (think) I followed correctly the instructions, but all I see is
?? Updates 
and empty card

**Comment by ludeeus** [comment]
@claudioita 
Can you paste both card and component config?

**Comment by claudioita** [comment]
```

resources:
  - url: /local/tracker-card.js?v=0
    type: js
```

```

      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
```

![cattura](https://user-images.githubusercontent.com/23485319/44770517-9637fc00-ab68-11e8-9eaf-f3325ac99bfc.JPG)
