### ISSUE TITLE
Updated to 0.1.5 cutom_component shown, custom traker not

### ISSUE THREAD

**Issue by claudioita** [custom-cards/tracker-card#20]
HASSIO 0.79
sensor.custom_component_tracker is present under development tool the other sensor not

configuration.yaml

`
custom_updater:
`

lovelace configuration
```

resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
..............................................
      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

```

![cattura](https://user-images.githubusercontent.com/23485319/46256516-26d96300-c4ac-11e8-903c-dc500eb7411b.GIF)

**Comment by ludeeus** [comment]
Card tracker are now an optional option of the custom_updater, that you need to manually define.
```yaml
custom_updater:
  track:
    - cards
    - components
```
<https://github.com/custom-components/custom_updater/wiki/Installation#configuration-option-track>
