### ISSUE TITLE
Tracker Card does not have any version

### ISSUE THREAD

**Issue by TheZoker** [custom-cards/tracker-card#26]
It seems for some reason, that the tracker card itself does not have any version:
![screenshot_2018 11 08_12h52m38s_016_](https://user-images.githubusercontent.com/1368405/48197194-52762580-e355-11e8-9570-0c943d17e0b1.png)

My config looks like this:
```
custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
```
