### ISSUE TITLE
Not showing mini-media player custom card

### ISSUE THREAD

**Issue by point-4ward** [custom-cards/tracker-card#27]
Hi all,

I have 

```
custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
```

and in lovelace

```
      - id: updater
        type: custom:tracker-card
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
```

Url is correct for the mini-media-player card JSON thingy, but it is not showing on the card.  The card is only showing tracker-card under cards, and custom_updater uner components (both at most up-to-date versions).

Ideas?

**Comment by ludeeus** [comment]
and how did you include that file in lovelace?

**Comment by point-4ward** [comment]
```
resources:
  - url: /local/mini-media-player-bundle.js
    type: module

  - url: /local/tracker-card.js?v=0.1.5
    type: js
```

All of my lovelace stuff is just in one big file, nothing split out.

**Comment by ludeeus** [comment]
This component needs that the resources have `?v=x.x.x` at the end to show it.

**Comment by point-4ward** [comment]
Ah, ok - I'll sort it in a bit - cheers 👍

**Comment by Wibias** [comment]
How do you end up fixing it? For me it wont work.

It looks like this for me:

```
resources:

  - url: /local/mini-media-player-bundle.js?v=1.0.0
    type: module
  - url: /local/tracker-card.js?v=0.1.5
    type: js
```

```
custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
```
