### ISSUE TITLE
Card shows updates for components although they are explicitly commented out in config

### ISSUE THREAD

**Issue by schneekluth** [custom-cards/tracker-card#29]
I use the custom_component for [hue sensors](https://github.com/robmarkcole/Hue-sensors-HASS). Lately there is some development going on and for me the latest stable 0.8 works best. Therefore I told the configuration file to ignore this component but the tracker card still shows the with avaiable update. Is this caused by the custom_component or by the tracker card?

Here is my configuration:

```YAML
custom_updater:
  show_installable: False
  track:
    - cards
    - components
  component_urls:
  # - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json
```

and this is how the tracker card looks like:

![card_issue](https://user-images.githubusercontent.com/5740913/51441246-f2deb380-1ccf-11e9-80e6-6335564e1e03.png)
