### ISSUE TITLE
Slider-entity-row component

### ISSUE THREAD

**Issue by adrianmihalko** [custom-cards/tracker-card#37]
I am using custom_updater 4.0, my config:

```
custom_updater:
  mode: storage
  track:
    - cards
  card_urls:
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

resources:
  - type: module
    url: /customcards/simple-thermostat.js
  - type: module
    url: /customcards/lovelace-slider-entity-row/slider-entity-row.js
  - type: module
    url: /customcards/mini-graph-card-bundle.js
  - type: js
    url: /customcards/tracker-card.js
```

I have two questions:

- Without `mode: storage` mini-graph-card was not shown.
- Slider-entity-row is not added in cards_urls, but it is tracked? It is hard coded into module?

And one suggestion:

 On hover there is a text select cursor for buttons, that is not the best for a click button:

![55b03d1b9e100e8b47677539dca610fa2e8dd421](https://user-images.githubusercontent.com/733361/52901339-b89b0000-3202-11e9-92f4-ae936bf5d5e3.jpeg)
