### ISSUE TITLE
tracker-card integration into lovelace inconsistent

### ISSUE THREAD

**Issue by juan11perez** [custom-cards/tracker-card#4]
Im getting this error on the card rendering: "please at least one tracker"

- type: custom:tracker-card

**Comment by ludeeus** [comment]
If you look at the install steps for this card you will see that you need to supply trackers to use it:
https://github.com/custom-cards/tracker-card#installation

```
- type: custom:tracker-card
  title:
  trackers:
    - sensor.custom_card_tracker
    - sensor.custom_component_tracker
```
