### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by DavidFW1960** [custom-cards/tracker-card#42]
Did a new install (was talking with another member and I noticed some changes)

The old config was:
 ```
Configure Lovelace to load the card:.
resources:
  - url: /customcards/tracker-card.js
    type: js
```

now you show:
```
Configure Lovelace to load the card:.
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
```
Now I also had the 2 js files in the /www/ folder...

But... When I changed to the new config (and the guy from the forum as well who was adding for the first time) the tracker created a folder www/github/custom-cards but it never downloaded the js files and there is nowhere in the instructions saying the js cards should be manually downloaded.

So please clarify the instructions?

Also my friend did a minimal config of the card (once we manually downloaded the js files)

The docs still say that 
![image](https://user-images.githubusercontent.com/36390762/53068484-cadfab80-352c-11e9-99b4-154f17e7782b.png)

the trackers are optional but it seems they may not be needed anymore?

Can you clarify please?
