### ISSUE TITLE
New installation fails...

### ISSUE THREAD

**Issue by mshrem** [custom-cards/tracker-card#47]
Ok so after a lot of reading i was able to get the card to show up however i dont think its showing my only custom component. 

First the only way for me to get the card to show up on the webfront was to copy the teacker-card.js to the www folder and then added this to the config : 

```
resources:
  - url: /local/tracker-card.js?track=true
    type: js
```
As long as i tried to follow the instructions for a new installation i could never get it to show up on the front end. 

now my config goes something like this : 

```
custom_updater:
  show_installable: False
  mode: storage
  track:
    - components
    - cards
  component_urls:
    - https://raw.githubusercontent.com/smartHomeHub/SmartIR/master/custom_components.json
```
Should i add some lines to the config file in order to track the card??? or am i missing something. 

Also  as you can see i have a custom component but its not showing up all i have is this : 
![card](https://user-images.githubusercontent.com/560713/53215512-9811e200-3616-11e9-940f-718a4f65844f.png)

**Comment by ludeeus** [comment]
If you use the new installation method, you need to run the service for it to download the card.

Can you post the config for the card?

**Comment by mshrem** [comment]
Well i followed along with the Gif .... and the card didn't downloaded when i ran the service.....  I just wanted to make sure if i am not doing something wrong ... do we need the card url on the config file ??? 

The card config is : 

`type: 'custom:tracker-card'`

**Comment by ludeeus** [comment]
That is fine, add the debug logs for the component please

**Comment by mshrem** [comment]
sure thing give me few hours i am not home yet.

**Comment by talondnb** [comment]
I get this too:

2019-02-23 08:54:54 ERROR (MainThread) [pyupdate.log] CustomCards(yaml_resources) - Lovelace config in yaml file not found
2019-02-23 08:54:54 ERROR (MainThread) [pyupdate.log] CustomCards(yaml_resources) - Lovelace config in yaml file not found
2019-02-23 08:55:08 ERROR (MainThread) [custom_components.custom_updater] Tried to serve up '/config/www/github/custom-cards/tracker-card.js' but it does not exist

**Comment by ludeeus** [comment]
You are using storage mode @talondnb you need to add `mode: storage` to the component.
https://github.com/custom-components/custom_updater/wiki/Installation#configuration-option-mode

**Comment by ludeeus** [comment]
@mshrem Before you post your logs, can you try with this config?

```yaml
custom_updater:
  mode: storage
  component_urls:
    - https://raw.githubusercontent.com/smartHomeHub/SmartIR/master/custom_components.json
```
